### PR TITLE
ARCH-6354: Optimize `Get/SetFieldValue()` to use integer indexes instead of search in Dictionary by string field name

### PR DESCRIPTION
**Pull request by SergeiPavlov**
The `[Field]` properties inside class are sorted in order of `MetadataToken` value.

Properties, inherited from base class are first.

### CODE REVIEW

**Comment by botinko** [comment]
@SergeiPavlov check failed tests, I saw `Index was outside the bounds of the array.`

**Review by botinko — APPROVED** [review]
Looks very complex as it requires a lot of immersion in the code to understand the complexity of the algorithm. There is a serious lack of a test that would handle significant cases in `BuildPersistentFields` and `GetBaseFields`.

**Comment by SergeiPavlov** [comment]
> There is a serious lack of a test that would handle significant cases in `BuildPersistentFields` and `GetBaseFields`.

I'm relying on existing tests. Looks like they cover all non-trivial cases (virtual Fields, fields from interfaces, `new` fields, recycled fields).  During developement of this implementation I investigated many failed tests and improvend the implementation to satisfy them.

Anyway I have not merged it into `master-servicetitan`, lets test it for a while on ST app.

**Comment by botinko** [comment]
@SergeiPavlov 
I see, that existent tests covers many cases. 
I suspect that in the long run the lack of dedicated tests for this feature will make maintaining and developing this code problematic. The code is forgotten very quickly and after a couple of months it will no longer be possible to figure it out.
Tests give at least some chance to understand the logic and important features of the code. 

I would just collect all non-trivial cases (virtual Fields, fields from interfaces, new fields, recycled fields, structs) in some test fixture.

**Comment by SergeiPavlov** [comment]
> I would just collect all non-trivial cases (virtual Fields, fields from interfaces, new fields, recycled fields, structs) in some test fixture.

This would be copy/pasting existing tests

**Pull request merged**
