### PR TITLE
Upgrade `Npgsql`

### PR DESCRIPTION
**Pull request by SergeiPavlov**
Resolve breaking changes in API

### CODE REVIEW

**Review by botinko — APPROVED** [review]
Note, that there was an NpgSql Client upgrade issue in mono. It could iterfere with this PR like block updating to lastes DO in mono without fixing copability issues in mono.

**Comment by SergeiPavlov** [comment]
> mono

Do you mean https://github.com/dataObjects-net/dataobjects-net as "mono"?

Yes, and I think they don't upgrade because nobody asks for it.
I'm going to setup Unit testing of DO-on-Postgresql configuration to be sure we don't break anything

**Comment by botinko** [comment]
> > mono
> 
> Do you mean https://github.com/dataObjects-net/dataobjects-net as "mono"?
> 
> Yes, and I think they don't upgrade because nobody asks for it. I'm going to setup Unit testing of DO-on-Postgresql configuration to be sure we don't break anything

I ment ST App Mono. Sorry, couldn't find the original thread with issue. Maybe it is not related.

**Comment by SergeiPavlov** [comment]
> I ment ST App Mono. Sorry, couldn't find the original thread with issue. Maybe it is not related.

Yes, I see incompatibility with `Npgsql.EntityFrameworkCore.PostgreSQL`  https://teamcity.st.dev/buildConfiguration/BAP_PlatformDotnet_IntegrationTests/4811150?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildChangesSection=true&expandPull+Request+Details=true&pluginCoverage=true&expandBuildTestsSection=true

We have to synchronize `EntityFramework` Nugets with the current .NET version
It is still `6.0.7`

@Mee7891 has already upgraded it in the `70neptune`

**Pull request merged**
