### PR TITLE
Disable publishing unused packages

### PR DESCRIPTION
**Pull request by SergeiPavlov**
Commented instead of removing to minimize merge conflicts from upstream

### CODE REVIEW

**Comment by botinko** [comment]
Why do we need this? Saving some KB of data in nupkg doesn't really matter.

**Comment by SergeiPavlov** [comment]
It is not necessary but saves some seconds on every publishing.

**Comment by botinko** [comment]
> It is not necessary but saves some seconds on every publishing.

If it's the only reason, I wouldn't do it.

**Review by botinko — CHANGES_REQUESTED** [review]
For me it's undesirable to make more difference between ST fork and official DO.

**Comment by SergeiPavlov** [comment]
> For me it's undesirable to make more difference between ST fork and official DO.

The big divergence is inevitable
The are many PRs pending on https://github.com/DataObjects-NET/dataobjects-net/pulls  which are alredy applied to our DO fork. There are little hope they will be approved nearest months

**Review by botinko — APPROVED** [review]

**Pull request merged**
