### PR TITLE
Make .ForEach() extension [Obsolete]; refactor to foreach

### PR DESCRIPTION
**Pull request by SergeiPavlov**
This change is for ST app 
As first step to get rid of  `.ForEach()` usage (it is used now in ~thousand places)..
Like 2 years ago we removed `.BadForEach()` extension

### CODE REVIEW

**Comment by botinko** [comment]
During last discussion https://servicetitan.slack.com/archives/GD2910GBS/p1617906508012700 it looks like we won't come to the conclusion, that it is really worth getting rid of ForEach extension. 
Why do we care about this problem in the DO repo?

**Comment by SergeiPavlov** [comment]
Just to be consistent and remove this pattern from ST app
That is why I'm commiting this change into our DO version, but not to upstream.
Basically `[Obsolete]` attribute fould be enough

**Comment by botinko** [comment]
How about making this ForEach extension internal? Obsoleting usually won't force somebody to make a fix.

**Comment by SergeiPavlov** [comment]
> How about making this ForEach extension internal? Obsoleting usually won't force somebody to make a fix.

It would be breaking change on this stage, because ST app uses it in many places.
After we convert all ST usages to `foreach` statement, we can make it internal

**Review by botinko — APPROVED** [review]

**Pull request merged**
